name = "dicom_write"

[dependencies]
dcmfx_core = { path = "../../../src/gleam/dcmfx_core" }
dcmfx_p10 = { path = "../../../src/gleam/dcmfx_p10" }
gleam_stdlib = ">= 0.41.0 and < 2.0.0"

[javascript]
deno = { allow_read = true, allow_write = true }
