name = "dcmfx_cli"
description = "DCMfx CLI tool"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.6.0"

[dependencies]
argv = ">= 1.0.2 and < 2.0.0"
birl = ">= 1.7.1 and < 2.0.0"
dcmfx_anonymize = { path = "../dcmfx_anonymize" }
dcmfx_character_set = { path = "../dcmfx_character_set" }
dcmfx_core = { path = "../dcmfx_core" }
dcmfx_json = { path = "../dcmfx_json" }
dcmfx_p10 = { path = "../dcmfx_p10" }
dcmfx_pixel_data = { path = "../dcmfx_pixel_data" }
file_streams = ">= 1.2.2 and < 2.0.0"
gleam_stdlib = ">= 0.43.0 and < 2.0.0"
glint = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
snag = ">= 0.3.0 and < 1.0.0"
term_size = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
deno = { allow_read = true, allow_write = true }
